version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
