version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  timescale:
    image: timescale/timescaledb:latest-pg16
    container_name: timescale
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${TIMESCALE_USER}
      - POSTGRES_PASSWORD=${TIMESCALE_PASSWORD}
      - POSTGRES_DB=${TIMESCALE_DB}
      - TIMESCALEDB_TELEMETRY=off
    restart: unless-stopped

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: ot-collector
    ports:
      - "4318:4318"
    command: "--config /etc/otelcol/config.yaml"
    volumes:
      - ./deployment_linux/collector-config.yaml:/etc/otelcol/config.yaml
    environment:
      - TEMPO_USERNAME=${TEMPO_USERNAME}
      - TEMPO_PASSWORD=${TEMPO_PASSWORD}
      - TEMPO_URL=${TEMPO_URL}
      - PROMETHEUS_USERNAME=${PROMETHEUS_USERNAME}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
    restart: unless-stopped
