name: Contributing Guidelines

on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on new issue
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.payload.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const commentBody = `Thank you for opening an issue! Please make sure to read the contributing guidelines [CONTRIBUTING.md](https://github.com/${owner}/${repo}/blob/main/CONTRIBUTING.md)`;

            const response = await github.issues.createComment({
              owner,
              repo,
              issue_number: issueNumber,
              body: commentBody,
            });
            console.log(response);
