name: Tests on Pull Request

on:
  pull_request:
    branches: [ '*' ]
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest