name: Tests on Merge Main

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest