name: Tests on Pull Request

on:
  pull_request:
    branches: ["*"]
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 5s
          --health-retries 20
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create database
        run: psql -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }} -d postgres -a -f sql_scripts/create_db.sql
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_LITESTAR_APP: SimplyTransport.app:create_app
          file_name: .env

      - name: Populate GTFS test data
        run: echo "y" | litestar importgtfs -dir ./tests/gtfs_test_data/TFI/

      - name: Run tests
        run: pytest
