name: Tests on Merge Main

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: stuser
            POSTGRES_PASSWORD: stpassword
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest